#--- Dockerfile-prod ---
FROM gradle:8.5-jdk17 AS builder
WORKDIR /usr/src/app

COPY . /usr/src/app

RUN gradle wrapper --gradle-version 8.5
RUN ./gradlew clean build -x test

FROM openjdk:17-jdk-alpine
COPY --from=builder /usr/src/build/libs/napzak-0.0.1-SNAPSHOT.jar /app/napzak.jar

# prod 프로파일로 실행
ENTRYPOINT ["java", "-jar", "/app/napzak.jar", "--spring.profiles.active=prod"]
