FROM gradle:8.8-jdk17 AS builder
WORKDIR /usr/src/app

COPY . .

RUN chmod +x ./gradlew && ./gradlew :api-server:bootJar -x test

FROM eclipse-temurin:17-jdk

RUN apt-get update && \
    apt-get install -y tzdata && \
    rm -rf /var/lib/apt/lists/*

ENV TZ=Asia/Seoul
ENV JAVA_TOOL_OPTIONS="-Duser.timezone=Asia/Seoul -Xms128m -Xmx384m"

WORKDIR /app

COPY --from=builder /usr/src/app/api-server/build/libs/api-server.jar /app/api-server.jar

ENTRYPOINT ["java", "-jar", "/app/api-server.jar", "--spring.profiles.active=dev", "--spring.config.additional-location=file:/app/application-dev.yml"]