version: "3.8"

services:
  api-server-blue:
    image: 203918864903.dkr.ecr.ap-northeast-2.amazonaws.com/napzak-api-prod:latest
    container_name: napzak-api-blue-prod
    ports: ["8080:8080"]
    networks: ["napzak-prod-net"]
    restart: always

networks:
  napzak-prod-net:
    external: true