FROM gradle:8.8-jdk17 AS builder
WORKDIR /usr/src

# 로컬에 있는 모든 소스 복사
COPY . /usr/src

# 빌드 (테스트 스킵)
RUN chmod +x ./gradlew
RUN ./gradlew clean build -x test

FROM openjdk:17-jdk-alpine
WORKDIR /app
COPY --from=builder /usr/src/build/libs/napzak-0.0.1-SNAPSHOT.jar /app/napzak.jar

ENTRYPOINT ["java", "-jar", "/app/app.jar", "--spring.profiles.active=prod"]
