version: "3.8"

services:
  api-server-blue:
    image: ${ECR_HOST}/${ECR_APP_NAME}:${IMAGE_TAG}
    container_name: napzak-api-blue-prod

    ports:
      - "8080:8080"

    environment:
      FIREBASE_CONFIG_PATH: file:/app/firebase/napzak-firebase-adminsdk.json

    volumes:
      - /home/ubuntu/Napzak-BE/secrets/prod/api/application-prod.yml:/app/application-prod.yml:ro
      - /home/ubuntu/Napzak-BE/secrets/prod/api/napzak-firebase-adminsdk.json:/app/firebase/napzak-firebase-adminsdk.json:ro

    networks:
      - napzak-prod-net

    restart: always

networks:
  napzak-prod-net:
    external: true