FROM gradle:8.8-jdk17 AS builder
WORKDIR /usr/src

# 필요한 파일 복사
COPY gradlew /usr/src/gradlew
COPY gradle /usr/src/gradle
COPY settings.gradle build.gradle ./
COPY src /usr/src/src

# 실행 권한 추가
RUN chmod +x ./gradlew

# Gradle 명령 실행
RUN ./gradlew dependencies --refresh-dependencies

FROM openjdk:17-jdk-alpine
WORKDIR /app
COPY --from=builder /usr/src/build/libs/napzak-0.0.1-SNAPSHOT.jar /app/napzak.jar

ENTRYPOINT ["java", "-jar", "/app/napzak.jar", "--spring.profiles.active=dev"]
