version: "3.8"

services:
  napzak-dev:
    container_name: napzak-dev
    image: "sailin1367/napzak-dev:latest"
    ports:
      - "8080:8080"
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - napzak-dev-net

  redis:
    container_name: napzak-dev-redis
    image: redis:7.0-alpine
    command: ["redis-server", "--requirepass", "napzakdev"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "napzakdev", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - napzak-dev-net
    restart: always  # 컨테이너가 종료되면 자동 재시작

networks:
  napzak-dev-net:
    driver: bridge