version: "3.8"

services:
  redis:
    container_name: napzak-prod-redis
    image: redis:7.0-alpine
    command: ["redis-server", "--requirepass", "napzakprod"]
    ports: ["6379:6379"]
    volumes: ["redis_data:/data"]
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "napzakprod", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      napzak-prod-net:
        aliases:
          - redis
          - napzak-prod-redis
    restart: always

  rabbitmq:
    container_name: napzak-prod-rabbitmq
    image: rabbitmq:3.12-management
    ports:
      - "5672:5672"
      - "15672:15672"
      - "61613:61613"
    environment:
      RABBITMQ_DEFAULT_USER: napzak_user
      RABBITMQ_DEFAULT_PASS: napzak_pw
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      napzak-prod-net:
        aliases:
          - rabbitmq
          - napzak-prod-rabbitmq
    restart: always

networks:
  napzak-prod-net:
    external: true

volumes:
  redis_data:
