name: dev-CD

on:
  push:
    branches: [ "develop" ]

jobs:
  CI:
    runs-on: ubuntu-22.04
    environment: dev

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle', '**/gradle-wrapper.properties') }}
          restore-keys: gradle-${{ runner.os }}-

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Create secret config file
        run: |
          mkdir -p src/main/resources
          echo "${{ secrets.APPLICATION_DEV }}" > src/main/resources/application-dev.yml
          ls -la src/main/resources
          cat src/main/resources/application-dev.yml

      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew clean build -x test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.9.1

      - name: Login to Docker Hub
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.DEV_DOCKERHUB_USERNAME }}
          password: ${{ secrets.DEV_DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile-dev
          push: true
          tags: ${{ secrets.DEV_DOCKERHUB_USERNAME }}/${{ secrets.DEV_REPONAME }}:latest

  CD:
    needs: [CI]
    runs-on: ubuntu-22.04
    environment: dev

    steps:
      - name: Docker Image Pull and Run
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_SERVER_HOST }}
          username: ${{ secrets.DEV_SERVER_USERNAME }}
          key: ${{ secrets.DEV_SERVER_KEY }}
          script: |
            bash /home/ubuntu/Napzak-BE/deploy.sh