name: prod-chat-CD

on:
  push:
    branches: [ "main" ]

jobs:
  build-push:
    runs-on: ubuntu-22.04
    environment: prod

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Inject CHAT secrets
        run: |
          printf '%s' "${{ secrets.CHAT_APPLICATION_PROD }}" > chat-server/src/main/resources/application-chat-prod.yml
          mkdir -p chat-server/src/main/resources/firebase
          printf '%s' "${{ secrets.CHAT_FIREBASE_JSON_B64 }}" | base64 -d \
            > chat-server/src/main/resources/firebase/napzak-firebase-adminsdk.json

      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.PROD_DOCKERHUB_USERNAME }}
          password: ${{ secrets.PROD_DOCKERHUB_TOKEN }}

      - name: Build & push CHAT image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile-chat-prod
          push: true
          tags: ${{ secrets.PROD_DOCKERHUB_USERNAME }}/napzak-chat-prod:latest

  deploy:
    needs: build-push
    runs-on: ubuntu-22.04
    environment: prod

    steps:
      - name: SSH deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_CHAT_SERVER_HOST }}
          username: ${{ secrets.PROD_SERVER_USERNAME }}
          key: ${{ secrets.PROD_CHAT_SERVER_KEY }}
          script: |
            bash /home/ubuntu/Napzak-BE/deploy.sh
