# prod-api-CI.yml
name: prod-api-CI

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - "api-server/**"
      - "common-module/**"
      - "core-domain/**"
      - ".github/workflows/prod-api-*.yml"

jobs:
  build:
    runs-on: ubuntu-22.04
    environment: prod

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      # Secret 파일 주입 (API)
      - name: Inject API secrets
        run: |
          printf '%s' "${{ secrets.API_APPLICATION_PROD }}" > api-server/src/main/resources/application-api-prod.yml
          mkdir -p api-server/src/main/resources/firebase
          printf '%s' "${{ secrets.API_FIREBASE_JSON_B64 }}" | base64 -d \
            > api-server/src/main/resources/firebase/napzak-firebase-adminsdk.json

      - name: Build (Gradle)
        run: |
          chmod +x ./gradlew
          ./gradlew clean build -x test