name: prod-api-CD

on:
  push:
    branches: [ "main" ]

jobs:
  build-push:
    runs-on: ubuntu-22.04
    environment: prod-api

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Inject API secrets
        run: |
          echo "${{ secrets.API_APPLICATION_PROD }}" > api-server/src/main/resources/application-api-prod.yml
          mkdir -p api-server/src/main/resources/firebase
          echo "${{ secrets.API_FIREBASE_JSON }}" > api-server/src/main/resources/firebase/napzak-firebase-adminsdk.json

      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.PROD_DOCKERHUB_USERNAME }}
          password: ${{ secrets.PROD_DOCKERHUB_TOKEN }}

      - name: Build & push API image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile-api-prod
          push: true
          tags: ${{ secrets.PROD_DOCKERHUB_USERNAME }}/napzak-api-prod:latest

  deploy:
    needs: build-push
    runs-on: ubuntu-22.04
    environment: prod-api

    steps:
      - name: SSH deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_API_SERVER_HOST }}
          username: ${{ secrets.PROD_SERVER_USERNAME }}
          key: ${{ secrets.PROD_API_SERVER_KEY }}
          script: |
            bash /home/ubuntu/Napzak-BE/deploy.sh
