name: prod-chat-CD

on:
  push:
    branches: [ "main" ]

env:
  ECR_HOST: ${{ secrets.CHAT_ECR_HOST }}
  ECR_APP_NAME: ${{ secrets.CHAT_ECR_APP_NAME }}
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-push:
    runs-on: ubuntu-22.04
    environment: prod

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Inject CHAT secrets
        run: |
          printf '%s' "${{ secrets.CHAT_APPLICATION_PROD }}" > chat-server/src/main/resources/application-chat-prod.yml
          mkdir -p chat-server/src/main/resources/firebase
          printf '%s' "${{ secrets.CHAT_FIREBASE_JSON_B64 }}" | base64 -d \
            > chat-server/src/main/resources/firebase/napzak-firebase-adminsdk.json

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_CHAT_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_CHAT_SECRET_KEY }}
          aws-region: ap-northeast-2

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ap-northeast-2 | \
          docker login --username AWS --password-stdin ${{ env.ECR_HOST }}

      - name: Ensure ECR repository exists
        run: |
          aws ecr describe-repositories --repository-names "${{ env.ECR_APP_NAME }}" >/dev/null 2>&1 || \
          aws ecr create-repository --repository-name "${{ env.ECR_APP_NAME }}" >/dev/null

      - name: Build & push API image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile-api-prod
          push: true
          tags: |
            ${{ env.ECR_HOST }}/${{ env.ECR_APP_NAME }}:${{ env.IMAGE_TAG }}
            ${{ env.ECR_HOST }}/${{ env.ECR_APP_NAME }}:latest

  deploy:
    needs: build-push
    runs-on: ubuntu-22.04
    environment: prod

    steps:
      - name: Chat deploy (auto blue-green)
        uses: appleboy/ssh-action@master
        env:
          ECR_HOST: ${{ env.ECR_HOST }}
          ECR_APP_NAME: ${{ env.ECR_APP_NAME }}
          IMAGE_TAG: ${{ env.IMAGE_TAG }}
        with:
          host: ${{ secrets.PROD_CHAT_SERVER_HOST }}
          username: ${{ secrets.PROD_SERVER_USERNAME }}
          key: ${{ secrets.PROD_CHAT_SERVER_KEY }}
          envs: ECR_HOST, ECR_APP_NAME, IMAGE_TAG
          script: |
            bash /home/ubuntu/Napzak-BE/deploy-blue-green.sh

      - name: Switch nginx upstream
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_API_SERVER_HOST }}
          username: ${{ secrets.PROD_SERVER_USERNAME }}
          key: ${{ secrets.PROD_API_SERVER_KEY }}
          script: |
            sudo /home/ubuntu/scripts/switch_chat_upstream.sh

      - name: Clean-up old chat container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_CHAT_SERVER_HOST }}
          username: ${{ secrets.PROD_SERVER_USERNAME }}
          key: ${{ secrets.PROD_CHAT_SERVER_KEY }}
          script: |
            bash /home/ubuntu/Napzak-BE/cleanup-chat-old.sh
        
